Hmmm... I've been getting a naming conflict, but I'm not sure the origin of it:
main.cpp: In function ‘int main()’:
main.cpp:41:49: error: call of overloaded
‘copy(std::vector<int>::iterator, std::vector<int>::iterator,
std::back_insert_iterator<std::vector<int> >)’ is ambiguous
     copy(v1.begin(), v1.end(), back_inserter(v2));
                                                 ^
In file included from ./algorithms/algorithms.h:45:0,
                 from main.cpp:5:
./algorithms/algorithms-implementation.h:75:6: note: candidate: void
copy(InputIterator, InputIterator, OutputIterator) [with InputIterator =
__gnu_cxx::__normal_iterator<int*, std::vector<int> >; OutputIterator =
std::back_insert_iterator<std::vector<int> >]
 void copy(InputIterator begin, InputIterator end, OutputIterator
destination) {
      ^
In file included from /usr/include/c++/5/bits/char_traits.h:39:0,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from main.cpp:1:
/usr/include/c++/5/bits/stl_algobase.h:462:5: note: candidate: _OI
std::copy(_II, _II, _OI) [with _II = __gnu_cxx::__normal_iterator<int*,
std::vector<int> >; _OI = std::back_insert_iterator<std::vector<int> >]
     copy(_II __first, _II __last, _OI __result)
     ^

It seems like std::copy is being included somehow, but I don't think I
do. I'm not using "using namespace std;", so what could be polluting the
namespace?